# Generated by Django 4.1.3 on 2023-01-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0029_rename_storage_key_file_file_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Scan",
        ),
    ]
