# Generated by Django 4.2.3 on 2023-08-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0030_delete_scan"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssertionsPerPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_assertions", models.PositiveIntegerField()),
                ("package_name", models.CharField(max_length=100)),
                ("package_uuid", models.UUIDField(unique=True)),
                ("url", models.URLField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Assertion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assertion_uuid", models.UUIDField(unique=True)),
                ("assertion_name", models.CharField(default=None, max_length=100)),
                (
                    "assertions_per_package",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="triage.assertionsperpackage",
                    ),
                ),
            ],
        ),
    ]
