#FROM nginx:alpine
#COPY .. /usr/share/nginx/html
#COPY ./site/ /usr/share/nginx/html/

# syntax=docker/dockerfile:1
FROM python:3-alphine
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /code/

EXPOSE 8001

CMD["python", "manage.py", "runserver", "0.0.0.0:8001"]